export const restaurantList = [
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "691297",
            name: "Reeves Royale Restaurant",
            uuid: "93910471-8860-45d6-8b6f-f5ae2ac16777",
            city: "87",
            area: "Bhanugudi",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "dc5264445465769eac73535cb6006a1a",
            cuisines: ["Biryani", "North Indian", "Chinese"],
            tags: [],
            costForTwo: 27000,
            costForTwoString: "₹270 FOR TWO",
            deliveryTime: 32,
            minDeliveryTime: 32,
            maxDeliveryTime: 32,
            slaString: "32 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
                restaurant: "reeves-royale-restaurant-bhanugudi-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No.13-1-22/1, 1st Floor, Opp. Chandana Bros, Main Road, Subhash Road, Kakinada, Kakinada (Urban), Kakinada, Andhra Pradesh-533001",
            locality: "Subhash Road",
            parentId: 414261,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7033569~p=1~eid=00000188-fbba-13f3-14b7-d9bf003e011a~srvts=1687850456051",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹249",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "691297",
                deliveryTime: 32,
                minDeliveryTime: 32,
                maxDeliveryTime: 32,
                lastMileTravel: 2.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.7",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "103033",
            name: "Food Park Family Restaurant",
            uuid: "4d03f128-acb2-4d5f-a24c-1cfe24c1d493",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "wuxfcmpwh9m1mfehl94x",
            cuisines: ["Indian", "Chinese", "Biryani"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 20,
            minDeliveryTime: 20,
            maxDeliveryTime: 20,
            slaString: "20 MINS",
            lastMileTravel: 2.5,
            slugs: {
                restaurant: "food-park-family-gandhi-nagar-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "8-5-22 ontimamidi junction ,gandhi park back side,gandhinagar",
            locality: "Gandhi Nagar",
            parentId: 12732,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "103033",
                deliveryTime: 20,
                minDeliveryTime: 20,
                maxDeliveryTime: 20,
                lastMileTravel: 2.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.7",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "93917",
            name: "Subbaiah Gari Hotel",
            uuid: "19239d86-2e3f-4092-990b-1346563667ef",
            city: "87",
            area: "Rama Rao Peta",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "h5zaigol7demozgsbyte",
            cuisines: ["South Indian"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 14,
            minDeliveryTime: 14,
            maxDeliveryTime: 14,
            slaString: "14 MINS",
            lastMileTravel: 2.4000000953674316,
            slugs: {
                restaurant: "subbaiah-gari-hotel-30-ramarao-peta-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "Nageswara Rao St  Rama Rao Peta  Kakinada  Andhra Pradesh 533004  India",
            locality: "Nageswara Rao Street",
            parentId: 196189,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.4 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ABOVE ₹749",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "93917",
                deliveryTime: 14,
                minDeliveryTime: 14,
                maxDeliveryTime: 14,
                lastMileTravel: 2.4000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "613255",
            name: "Vinayaka East Foods",
            uuid: "151da353-f90b-4d77-9e7b-f1790a2c8d17",
            city: "87",
            area: "Bhanugadi",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "lognqfmrezkq2vsiutd6",
            cuisines: ["North Indian", "Biryani", "Chinese"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 5.5,
            slugs: {
                restaurant: "vinayaka-east-foods-bhanugudi-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No.70-2-147/E Stadium Road Back Side, Ramanayyapeta, Kakinada,  East Godavari, Andhra Pradesh - 533005.",
            locality: "Ramanayyapeta",
            parentId: 365812,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2900,
                message: "",
                title: "Delivery Charge",
                amount: "2900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7033379~p=4~eid=00000188-fbba-13f3-14b7-d9c0003e043d~srvts=1687850456051",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "5.5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹349",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "613255",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 5.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.8",
            totalRatings: 500,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "93929",
            name: "Subbayya Gari Hotel OLD & ORIGINAL",
            uuid: "ea0246e7-7dfb-4273-b07a-2145d7a2ca0f",
            city: "87",
            area: "Rama Rao Peta",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "bdgtgldczdeo0dkexatc",
            cuisines: ["Andhra", "South Indian"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 14,
            minDeliveryTime: 14,
            maxDeliveryTime: 14,
            slaString: "14 MINS",
            lastMileTravel: 2.4000000953674316,
            slugs: {
                restaurant:
                    "subbayya-gari-hotel-old-original-rama-rao-peta-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "10 6 14  Subbayya Hotel Road  Rama Rao Peta  Kakinada  Andhra Pradesh 533001  India",
            locality: "Subbayya Hotel Road",
            parentId: 12737,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.4 kms",
            hasSurge: false,
            sla: {
                restaurantId: "93929",
                deliveryTime: 14,
                minDeliveryTime: 14,
                maxDeliveryTime: 14,
                lastMileTravel: 2.4000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "293526",
            name: "Vasista Multicuisine Restaurant",
            uuid: "ba306cd9-9834-41ec-8527-4248c39d3985",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "sbnb8c1tz16j0mk8phfd",
            cuisines: [
                "Biryani",
                "Chinese",
                "North Indian",
                "South Indian",
            ],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 17,
            minDeliveryTime: 17,
            maxDeliveryTime: 17,
            slaString: "17 MINS",
            lastMileTravel: 2.5999999046325684,
            slugs: {
                restaurant: "vasista-restaurant-bhanugudi-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address: "3 LIGHT JUNCTION, Kakinada, Andhra Pradesh 533004",
            locality: "Prakasam Street",
            parentId: 221633,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.5 kms",
            hasSurge: false,
            sla: {
                restaurantId: "293526",
                deliveryTime: 17,
                minDeliveryTime: 17,
                maxDeliveryTime: 17,
                lastMileTravel: 2.5999999046325684,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "293680",
            name: "Hyggee Multicuisine Restaurant",
            uuid: "b01eaf2b-4b7d-4c84-b7bf-10182192c9a2",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "5000+ ratings",
            cloudinaryImageId: "43d42aeba1a60b4203030e19cfe47eae",
            cuisines: ["Biryani", "North Indian", "Chinese"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 7.199999809265137,
            slugs: {
                restaurant:
                    "hyggee-multicuisine-restaurant-sarpavaram-sarpavaram",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No: 69-4-26, 1st Floor, Sarpavaram Junction, Kakinada",
            locality: "Sarpavaram",
            parentId: 12690,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4200,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4200,
                message: "",
                title: "Delivery Charge",
                amount: "4200",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7130270~p=7~eid=00000188-fbba-13f3-14b7-d9c1003e077d~srvts=1687850456051",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "7.1 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹249",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "293680",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 7.199999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.9",
            totalRatings: 5000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "689483",
            name: "Kshatriya Foods",
            uuid: "4df0e347-8db3-4abd-8c0c-70651b6e1716",
            city: "87",
            area: "Bhanugudi",
            totalRatingsString: "50+ ratings",
            cloudinaryImageId: "f594f4f63d3e00e93203f02d40e38d24",
            cuisines: ["Biryani", "South Indian", "Chinese"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 19,
            minDeliveryTime: 19,
            maxDeliveryTime: 19,
            slaString: "19 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
                restaurant: "kshatriya-foods-bhanugudi-bhanugudi-2",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No.20/1/25/6, Main Road, Kakinada, Kakinada (Urban), East Godavari,  Andhra Pradesh-533001",
            locality: "Kakinada",
            parentId: 19387,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            sla: {
                restaurantId: "689483",
                deliveryTime: 19,
                minDeliveryTime: 19,
                maxDeliveryTime: 19,
                lastMileTravel: 2.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 50,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "92986",
            name: "Meesala Raju Gari Hotel Ashoka Inn",
            uuid: "89ae66bb-b066-4e19-b107-0197740a188f",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "fce5e0b123533c2139cbccdab6b5e54a",
            cuisines: ["Biryani", "Andhra", "North Indian"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 25,
            minDeliveryTime: 25,
            maxDeliveryTime: 25,
            slaString: "25 MINS",
            lastMileTravel: 4.199999809265137,
            slugs: {
                restaurant:
                    "meesala-raju-gari-hotel-ashoka-inn-bhanugudi-junction-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "1-15-30, Opp. Pulse Hospital, Sriram Nagar, Kakinada - 533003",
            locality: "Kondayya Palem",
            parentId: 12741,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2400,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2400,
                message: "",
                title: "Delivery Charge",
                amount: "2400",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4.1 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "92986",
                deliveryTime: 25,
                minDeliveryTime: 25,
                maxDeliveryTime: 25,
                lastMileTravel: 4.199999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.8",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "435808",
            name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
            uuid: "3c16bfa4-2baa-4d47-8883-6dba9ad270e6",
            city: "87",
            area: "Kakinada Locality",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "s2hvq2qlp50g3sspfbop",
            cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 18,
            minDeliveryTime: 18,
            maxDeliveryTime: 18,
            slaString: "18 MINS",
            lastMileTravel: 3.5,
            slugs: {
                restaurant:
                    "kwality-walls-frozen-dessert-and-ice-cream-shop-bhanugudi-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "SRI SRINIVASA AGENCY'S: D.NO 15-9-9, SATHYAPRASANNA NAGAR, KAKINADA, EAST GODAVARI, ANDHRA PRADESH-533001",
            locality: "Bhanugudi",
            parentId: 582,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7162615~p=10~eid=00000188-fbba-13f3-14b7-d9c2003e0a69~srvts=1687850456051",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3.5 kms",
            hasSurge: false,
            sla: {
                restaurantId: "435808",
                deliveryTime: 18,
                minDeliveryTime: 18,
                maxDeliveryTime: 18,
                lastMileTravel: 3.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.3",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "458205",
            name: "KFC",
            uuid: "7c505db5-6c16-4100-8bc6-3c7751ca4265",
            city: "87",
            area: "Surya Rao Peta",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
            cuisines: [
                "Burgers",
                "Biryani",
                "American",
                "Snacks",
                "Fast Food",
            ],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 18,
            minDeliveryTime: 18,
            maxDeliveryTime: 18,
            slaString: "18 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
                restaurant: "kfc-kakinada-powerpet",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No 13-1-45, Main Road, Suryaraopet, East Godavari, Kakinada, Andhra Pradesh 533001",
            locality: "Ramasomayajulu Street",
            parentId: 547,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "458205",
                deliveryTime: 18,
                minDeliveryTime: 18,
                maxDeliveryTime: 18,
                lastMileTravel: 2.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "657472",
            name: "Burger King",
            uuid: "7782ee6b-97a3-4580-861a-ac80773cfcd0",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
            cuisines: ["Burgers", "American"],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            slaString: "24 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
                restaurant: "burger-king-surya-rao-peta-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No.13, 1-48, Main Rd, Surya Rao Peta, Kakinada, Andhra Pradesh 533001",
            locality: "Ramasomayajulu Street",
            parentId: 166,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "657472",
                deliveryTime: 24,
                minDeliveryTime: 24,
                maxDeliveryTime: 24,
                lastMileTravel: 2.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "613182",
            name: "Rajugari Vindhubojanam",
            uuid: "757fb11b-de7b-4064-84d3-857dc2b661d8",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "a10684129aaa0e41cff2c988a1d8d553",
            cuisines: [
                "Biryani",
                "Chinese",
                "North Indian",
                "South Indian",
            ],
            tags: [],
            costForTwo: 27000,
            costForTwoString: "₹270 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 5,
            slugs: {
                restaurant: "rajugari-vindhubojanam-bhanugudi-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "D.No. 70-7-7/1A, NFCL Road, Ramanayyapeta, Near Life Line Hospital,  Kakinada, Kakinada (Urban), East Godavari, Andhra Pradesh, 533003",
            locality: "Ramanayyapeta",
            parentId: 365786,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 2900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 2900,
                message: "",
                title: "Delivery Charge",
                amount: "2900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=7130281~p=13~eid=00000188-fbba-13f3-14b7-d9c3003e0d7b~srvts=1687850456051",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "613182",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.7",
            totalRatings: 500,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "381999",
            name: "Overaction",
            uuid: "09af2f52-f5a3-457e-b8d9-0942cf3d1a0a",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "pajqq7rzmy7d7tdo57gx",
            cuisines: ["Biryani", "Indian", "Tandoor"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 20,
            minDeliveryTime: 20,
            maxDeliveryTime: 20,
            slaString: "20 MINS",
            lastMileTravel: 2.200000047683716,
            slugs: {
                restaurant: "overaction-bhanugudi-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "Near ATCHUTAPURAM RAILWAY GATE, PINCODE : 533003davari, Andhra Pradesh-533003",
            locality: "Narasanna Nagar",
            parentId: 252212,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.2 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "UPTO ₹40",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "381999",
                deliveryTime: 20,
                minDeliveryTime: 20,
                maxDeliveryTime: 20,
                lastMileTravel: 2.200000047683716,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.7",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "107946",
            name: "Venky Residency",
            uuid: "6fae1991-59e0-4f16-9c17-647de2e7b32a",
            city: "87",
            area: "Kakinada",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "1d4c3c086a4a435bd74fb81858868362",
            cuisines: ["Indian", "Continental", "Tandoor", "Chinese"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 22,
            minDeliveryTime: 22,
            maxDeliveryTime: 22,
            slaString: "22 MINS",
            lastMileTravel: 2.9000000953674316,
            slugs: {
                restaurant: "venky-residency-salipeta-bhanugudi",
                city: "kakinada",
            },
            cityState: "87",
            address:
                "Fire Station, Door No. 12-1-28, Jawahar Street, Opposite Salipeta, Kakinada, Andhra Pradesh 533001",
            locality: "Jawahar Street",
            parentId: 12730,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 1900,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 1900,
                message: "",
                title: "Delivery Charge",
                amount: "1900",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "107946",
                deliveryTime: 22,
                minDeliveryTime: 22,
                maxDeliveryTime: 22,
                lastMileTravel: 2.9000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.6",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
]

export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_MENU_URL = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=16.9623047&lng=82.21175679999999&restaurantId=";

export const IMG_LOGO_URL = "https://static.vecteezy.com/system/resources/previews/011/468/885/original/food-logo-spoon-fork-icon-illustration-symbol-for-fast-delivery-app-restaurant-template-free-vector.jpg";